import { lobster, pretendard } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} bg-neutral-950 text-neutral-50`}
      >
        <nav className={lobster.className}>imianio</nav>
        {children}
      </body>
    </html>
  );
}
