import type { Metadata } from "next";

import { Lobster, Noto_Sans_KR } from "next/font/google";

import "./globals.css";

import Providers from "@/components/providers/providers";
import { cn } from "@/lib/utils";

const noto = Noto_Sans_KR({ subsets: ["latin"] });
const lobster = Lobster({
  weight: "400",
  subsets: ["latin"],
  variable: "--lobster",
});

export const metadata: Metadata = {
  title: "i'm ian!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn(lobster.variable, noto.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
