import Navigation from "@/components/Navigation";
import { pretendard } from "../styles/fonts";
import "../styles/globals.css";
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.className} bg-neutral-950 text-neutral-50 dark`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
